### ISSUE TITLE
Dragon Appeasement not offering draw

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#530] opened 2013-11-09 14:06 UTC
_From [onyx.dra...@gmail.com](https://code.google.com/u/113848138665444794590/) on July 31, 2012 02:52:48_

What steps will reproduce the problem? 1. Enchantment "Dragon Appeasement" in play
2. "Nantuko Husk" in play
3. Sacrifice "Elf Warrior" token to Nantuko Husk for +3/+3 What is the expected output? What do you see instead? Your draw phase should be skipped, Nantuko Husk should get a +3/+3, and you should be offered the choice to draw a card. Instead your draw phase is skipped, you get the +3/+3, and there seems to be no way to draw a card at all. What version of the product are you using? On what operating system? 0.18.6 Please provide any additional information below.

_Original issue: http://code.google.com/p/wagic/issues/detail?id=901_

**Comment by kevlahnota** [comment] 2016-06-09 13:43
It works correctly. Skip your draw step, so you have no draw step. and whenever you sacrifice a creature you draw a card.
![Dragon Appeasement](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=180616&type=card)

**Comment by kevlahnota** [comment] 2017-03-01 11:22
closing this, cant reproduce this

**Closed by kevlahnota** 2017-03-01 11:22 UTC
Labels: bug, CardsEngine, imported, invalid, Priority-Medium
