### ISSUE TITLE
The most recent Psp release of Wagic crashes when you try to Open the Store 

### ISSUE THREAD

**Issue by RampingZerg** [WagicProject/wagic#833] opened 2016-08-04 19:58 UTC
Is it just me ? Maybe my cfw clashes with Wagic

**Comment by kevlahnota** [comment] 2016-08-06 01:27
try resizing all graphic images into psp supported resolutions. Some members have produce image pack for psp since in this new release have hires images. http://wololo.net/forum/viewtopic.php?f=4&t=66296&p=97905#p97905

**Comment by kevlahnota** [comment] 2016-08-06 04:47
nevermind i see the issue will look into it

**Comment by kevlahnota** [comment] 2016-08-14 03:38
Do you still have crashes after resizing images to psp supported res?

**Comment by RampingZerg** [comment] 2016-08-15 22:11
i test the newest version atm , i got one crash right now , but i think that was caused by some older images . Iam resizing the new menu images atm , and test that without card images after iam done , hope that works

**Comment by kevlahnota** [comment] 2017-03-01 11:17
closed this since I cant reproduce this anymore, will reopen if the issue persist...

**Closed by kevlahnota** 2017-03-01 11:17 UTC
