### ISSUE TITLE
Add filter not working in Ask about part of store.

### ISSUE THREAD

**Issue by xawotihs** [WagicProject/wagic#532] opened 2013-11-09 14:06 UTC
_From [karl.han...@gmail.com](https://code.google.com/u/108160553103789660655/) on August 21, 2012 21:50:38_

What steps will reproduce the problem? 1. Open the store, go to "Ask about..."
2. Unable to "Add filter" What is the expected output? What do you see instead? Opening the filter menu. What version of the product are you using? On what operating system? Wagic 0.18.6 for Android, on Android 4.1.1 (Jellybean). Please provide any additional information below. Google Nexus 7

_Original issue: http://code.google.com/p/wagic/issues/detail?id=908_

**Comment by kevlahnota** [comment] 2017-03-01 11:21
cannot reproduce this anymore on latest android build, closing this...

**Closed by kevlahnota** 2017-03-01 11:21 UTC
Labels: bug, GameLogic, imported, Priority-Medium
